// ── Credentials de test (Phase 2 backend) ──
// admin@drmezhoud.dz / Admin123!
// patient@drmezhoud.dz / Patient123!

import type {
  User,
  Patient,
  Appointment,
  Service,
  DietPlan,
  Document,
  Testimonial,
  FAQ,
  DashboardStats,
  Medecin,
  Cabinet,
  Pathologie,
  Article,
  Temoignage,
  EtapeParcours,
} from "@/types"

export const mockUsers: User[] = [
  {
    id: "usr-001",
    email: "admin@drmezhoud.dz",
    passwordHash: "$2b$10$placeholder_admin_hash",
    nom: "Mezhoud",
    prenom: "Hadj",
    role: "ADMIN",
    telephone: "+213 21 63 12 45",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "usr-002",
    email: "patient@drmezhoud.dz",
    passwordHash: "$2b$10$placeholder_patient_hash",
    nom: "Ziani",
    prenom: "Fatima",
    role: "PATIENT",
    telephone: "+213 771 23 45 67",
    createdAt: "2025-03-15T09:30:00Z",
    updatedAt: "2026-06-20T14:00:00Z",
  },
  {
    id: "usr-003",
    email: "m.kader@email.dz",
    passwordHash: "$2b$10$placeholder_hash",
    nom: "Kader",
    prenom: "Mohamed",
    role: "PATIENT",
    telephone: "+213 772 34 56 78",
    createdAt: "2025-06-10T11:00:00Z",
    updatedAt: "2026-05-15T09:00:00Z",
  },
  {
    id: "usr-004",
    email: "s.bensalem@email.dz",
    passwordHash: "$2b$10$placeholder_hash",
    nom: "Bensalem",
    prenom: "Sarah",
    role: "PATIENT",
    telephone: "+213 773 45 67 89",
    createdAt: "2025-09-01T07:45:00Z",
    updatedAt: "2026-07-05T16:30:00Z",
  },
  {
    id: "usr-005",
    email: "k.djamel@email.dz",
    passwordHash: "$2b$10$placeholder_hash",
    nom: "Djamel",
    prenom: "Karim",
    role: "PATIENT",
    telephone: "+213 774 56 78 90",
    createdAt: "2024-11-20T13:00:00Z",
    updatedAt: "2026-04-28T11:15:00Z",
  },
  {
    id: "usr-006",
    email: "n.amel@email.dz",
    passwordHash: "$2b$10$placeholder_hash",
    nom: "Amel",
    prenom: "Nadia",
    role: "PATIENT",
    telephone: "+213 775 67 89 01",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-07-02T08:45:00Z",
  },
]

export const mockPatients: Patient[] = [
  {
    id: "pat-001",
    userId: "usr-002",
    dateNaissance: "1985-07-22",
    sexe: "F",
    groupeSanguin: "A+",
    taille: 165,
    poids: 72,
    allergies: "Pénicilline",
    antecedent: "Hypertension artérielle, MRC stade 3",
    medecinTraitant: "Dr Mezhoud Hadj",
    createdAt: "2025-03-15T09:30:00Z",
    updatedAt: "2026-06-20T14:00:00Z",
  },
  {
    id: "pat-002",
    userId: "usr-003",
    dateNaissance: "1972-11-05",
    sexe: "M",
    groupeSanguin: "O+",
    taille: 178,
    poids: 85,
    allergies: "Sulfamides",
    antecedent: "Diabète type 2, Néphropathie diabétique",
    medecinTraitant: "Dr Mezhoud Hadj",
    createdAt: "2025-06-10T11:00:00Z",
    updatedAt: "2026-05-15T09:00:00Z",
  },
  {
    id: "pat-003",
    userId: "usr-004",
    dateNaissance: "1990-03-18",
    sexe: "F",
    groupeSanguin: "AB-",
    taille: 170,
    poids: 63,
    allergies: "Aucune",
    antecedent: "Greffe rénale 2024, suivi post-transplantation",
    medecinTraitant: "Dr Mezhoud Hadj",
    createdAt: "2025-09-01T07:45:00Z",
    updatedAt: "2026-07-05T16:30:00Z",
  },
  {
    id: "pat-004",
    userId: "usr-005",
    dateNaissance: "1968-09-30",
    sexe: "M",
    groupeSanguin: "B+",
    taille: 182,
    poids: 95,
    allergies: "Iode",
    antecedent: "Lithiase urinaire récidivante, HTA",
    medecinTraitant: "Dr Mezhoud Hadj",
    createdAt: "2024-11-20T13:00:00Z",
    updatedAt: "2026-04-28T11:15:00Z",
  },
  {
    id: "pat-005",
    userId: "usr-006",
    dateNaissance: "1995-12-08",
    sexe: "F",
    groupeSanguin: "A-",
    taille: 160,
    poids: 58,
    allergies: "Aucune",
    antecedent: "Glomérulonéphrite chronique",
    medecinTraitant: "Dr Mezhoud Hadj",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-07-02T08:45:00Z",
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "apt-001",
    patientId: "pat-001",
    patientNom: "Ziani",
    patientPrenom: "Fatima",
    date: "2026-06-10",
    startTime: "09:00",
    endTime: "09:30",
    type: "Suivi de maladie rénale chronique",
    status: "COMPLETED",
    motif: "Suivi trimestriel MRC stade 3",
    notes: "Créatinine stable à 1.4 mg/dL. Poursuivre traitement actuel.",
    createdAt: "2026-05-20T10:00:00Z",
    updatedAt: "2026-06-10T10:00:00Z",
  },
  {
    id: "apt-002",
    patientId: "pat-002",
    patientNom: "Kader",
    patientPrenom: "Mohamed",
    date: "2026-06-15",
    startTime: "10:30",
    endTime: "11:00",
    type: "Consultation initiale",
    status: "COMPLETED",
    motif: "Bilan initial néphropathie diabétique",
    notes: "HbA1c à 8.2%. Débuter inhibiteur SGLT2. Contrôle dans 3 mois.",
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: "2026-06-15T11:30:00Z",
  },
  {
    id: "apt-003",
    patientId: "pat-003",
    patientNom: "Bensalem",
    patientPrenom: "Sarah",
    date: "2026-07-08",
    startTime: "14:00",
    endTime: "14:30",
    type: "Bilan pré-transplantation",
    status: "CONFIRMED",
    motif: "Bilan annuel post-greffe",
    notes: "",
    createdAt: "2026-06-25T09:00:00Z",
    updatedAt: "2026-06-30T12:00:00Z",
  },
  {
    id: "apt-004",
    patientId: "pat-004",
    patientNom: "Djamel",
    patientPrenom: "Karim",
    date: "2026-07-12",
    startTime: "09:00",
    endTime: "09:30",
    type: "Hypertension artérielle",
    status: "SCHEDULED",
    motif: "Suivi HTA et lithiase",
    notes: "",
    createdAt: "2026-07-01T14:00:00Z",
    updatedAt: "2026-07-01T14:00:00Z",
  },
  {
    id: "apt-005",
    patientId: "pat-005",
    patientNom: "Amel",
    patientPrenom: "Nadia",
    date: "2026-07-15",
    startTime: "11:00",
    endTime: "11:30",
    type: "Résultats d'analyses",
    status: "SCHEDULED",
    motif: "Résultats bilan semestriel",
    notes: "Prévoir échographie rénale de contrôle",
    createdAt: "2026-07-02T08:00:00Z",
    updatedAt: "2026-07-03T10:00:00Z",
  },
  {
    id: "apt-006",
    patientId: "pat-001",
    patientNom: "Ziani",
    patientPrenom: "Fatima",
    date: "2026-05-20",
    startTime: "09:00",
    endTime: "09:30",
    type: "Suivi de maladie rénale chronique",
    status: "CANCELLED",
    motif: "Contrôle créatinine",
    notes: "Annulé par la patiente. Reporté au 10/06.",
    createdAt: "2026-05-10T08:00:00Z",
    updatedAt: "2026-05-18T16:00:00Z",
  },
  {
    id: "apt-007",
    patientId: "pat-002",
    patientNom: "Kader",
    patientPrenom: "Mohamed",
    date: "2026-08-01",
    startTime: "10:00",
    endTime: "10:30",
    type: "Suivi de maladie rénale chronique",
    status: "SCHEDULED",
    motif: "Contrôle trimestriel néphropathie diabétique",
    notes: "",
    createdAt: "2026-07-05T11:00:00Z",
    updatedAt: "2026-07-05T11:00:00Z",
  },
  {
    id: "apt-008",
    patientId: "pat-003",
    patientNom: "Bensalem",
    patientPrenom: "Sarah",
    date: "2026-04-22",
    startTime: "14:30",
    endTime: "15:00",
    type: "Consultation initiale",
    status: "COMPLETED",
    motif: "Suivi post-greffe à 18 mois",
    notes: "Bonne fonction du greffon. Créatinine à 1.1 mg/dL. Pas de rejet.",
    createdAt: "2026-04-10T09:00:00Z",
    updatedAt: "2026-04-22T15:30:00Z",
  },
]

export const mockServices: Service[] = [
  {
    id: "svc-001",
    nom: "Consultation de néphrologie",
    description: "Consultation complète avec examen clinique, analyse des bilans et plan thérapeutique personnalisé.",
    duree: 30,
    prix: 3000,
    icone: "Stethoscope",
    actif: true,
  },
  {
    id: "svc-002",
    nom: "Suivi de maladie rénale chronique",
    description: "Suivi régulier des patients atteints de MRC à tous les stades, avec ajustement thérapeutique.",
    duree: 30,
    prix: 2500,
    icone: "Activity",
    actif: true,
  },
  {
    id: "svc-003",
    nom: "Prise en charge HTA",
    description: "Diagnostic, traitement et suivi de l'hypertension artérielle d'origine rénale ou essentielle.",
    duree: 30,
    prix: 2500,
    icone: "HeartPulse",
    actif: true,
  },
  {
    id: "svc-004",
    nom: "Échographie rénale",
    description: "Examen échographique des reins, voies urinaires et vessie avec Doppler si nécessaire.",
    duree: 20,
    prix: 4500,
    icone: "Scan",
    actif: true,
  },
  {
    id: "svc-005",
    nom: "Bilan pré-transplantation",
    description: "Évaluation complète avant transplantation rénale incluant bilans et consultations spécialisées.",
    duree: 60,
    prix: 6000,
    icone: "ClipboardList",
    actif: true,
  },
  {
    id: "svc-006",
    nom: "Suivi post-greffe",
    description: "Surveillance rapprochée après transplantation rénale pour prévenir le rejet et optimiser la fonction du greffon.",
    duree: 30,
    prix: 3000,
    icone: "Heart",
    actif: true,
  },
  {
    id: "svc-007",
    nom: "Conseil diététique rénal",
    description: "Consultation d'éducation nutritionnelle adaptée aux pathologies rénales avec remise de plans alimentaires.",
    duree: 45,
    prix: 2000,
    icone: "Droplets",
    actif: true,
  },
]

export const mockDietPlans: DietPlan[] = [
  {
    id: "diet-001",
    patientId: "pat-001",
    titre: "Régime hyposodé — Stade 3 MRC",
    description: "Plan alimentaire pauvre en sodium pour patiente MRC stade 3 avec HTA associée.",
    category: "Régime hyposodé",
    content: "<h2>Objectifs du régime</h2><p>Réduire l'apport sodé à moins de 2g/jour pour contrôler la tension artérielle et réduire la charge sur les reins.</p><h3>Aliments autorisés</h3><ul><li>Fruits et légumes frais (sauf ceux riches en potassium si indiqué)</li><li>Viandes maigres non salées</li><li>Poisson frais (sans sauce salée)</li><li>Huile d'olive, huile végétale</li><li>Pain sans sel, pâtes, riz (cuits sans sel)</li><li>Lait et yaourts nature (en quantité limitée)</li></ul><h3>Aliments à éviter</h3><ul><li>Charcuterie, fromages fermentés</li><li>Conserves, plats préparés</li><li>Bouillons cubes, sauces industrielles</li><li>Chips, apéritifs salés</li><li>Eaux minérales riches en sodium</li><li>Pain et biscottes du commerce</li></ul><p>Privilégier les herbes aromatiques et épices pour assaisonner (curcuma, persil, coriandre, cumin).</p>",
    dateDebut: "2026-06-15",
    dateFin: "2026-09-15",
    createdAt: "2026-06-10T10:00:00Z",
  },
  {
    id: "diet-002",
    patientId: "pat-002",
    titre: "Régime pour diabétique néphropathe",
    description: "Plan nutritionnel contrôlant la glycémie et protégeant la fonction rénale.",
    category: "Régime pour diabétique",
    content: "<h2>Objectifs du régime</h2><p>Maintenir un bon équilibre glycémique tout en protégeant la fonction rénale. Apport calorique adapté pour un IMC cible de 25.</p><h3>Principes clés</h3><ul><li>Répartition des glucides sur 3 repas + 2 collations</li><li>Index glycémique bas à modéré</li><li>Protéines : 0.8 g/kg/jour</li><li>Sodium : < 2g/jour</li><li>Fibres : 25-30g/jour</li></ul><h3>Exemple de menu type</h3><p>Petit-déjeuner : Pain complet + fromage blanc 0% + thé vert</p><p>Déjeuner : Salade verte + poisson grillé + légumes vapeur + 1 fruit</p><p>Dîner : Soupe de légumes maison + volaille grillée + quinoa</p>",
    dateDebut: "2026-06-20",
    dateFin: "2026-09-20",
    createdAt: "2026-06-15T11:00:00Z",
  },
  {
    id: "diet-003",
    patientId: "pat-003",
    titre: "Régime post-transplantation",
    description: "Plan nutritionnel pour prévenir les complications après greffe rénale.",
    category: "Régime post-transplantation",
    content: "<h2>Objectifs du régime</h2><p>Prévenir la prise de poids, l'hypertension, le diabète post-greffe et les carences nutritionnelles dues aux immunosuppresseurs.</p><h3>Recommandations</h3><ul><li>Apport protéique : 1.2-1.5 g/kg/jour (phase de cicatrisation)</li><li>Sodium : < 3g/jour</li><li>Potassium : libre sauf si hyperkaliémie</li><li>Phosphore : apport normal</li><li>Calcium : 1000-1200 mg/jour</li></ul><h3>Aliments à privilégier</h3><ul><li>Fruits et légumes bien lavés ou cuits</li><li>Viandes et poissons cuits à cœur</li><li>Produits laitiers pasteurisés</li><li>Eau filtrée ou en bouteille</li></ul><p>Éviter les aliments crus ou non pasteurisés (risque infectieux lié aux immunosuppresseurs).</p>",
    dateDebut: "2026-07-01",
    dateFin: "2026-12-31",
    createdAt: "2026-06-28T09:00:00Z",
  },
  {
    id: "diet-004",
    patientId: "pat-004",
    titre: "Régime contrôlé en potassium — Lithiase",
    description: "Plan alimentaire pauvre en potassium pour patient avec lithiase et hyperkaliémie modérée.",
    category: "Régime contrôlé en potassium",
    content: "<h2>Objectifs du régime</h2><p>Limiter l'apport en potassium à 2-3g/jour pour éviter l'hyperkaliémie et ses complications cardiaques.</p><h3>Aliments à limiter</h3><ul><li>Banane, abricot, kiwi, avocat, fruit sec</li><li>Pomme de terre, épinards, champignon</li><li>Légumes secs, céréales complètes</li><li>Chocolat, café soluble</li></ul><h3>Aliments autorisés</h3><ul><li>Pomme, poire, raisin, pastèque</li><li>Carotte, courgette, concombre</li><li>Pâtes, riz, semoule (cuits à l'eau, eau jetée)</li></ul>",
    dateDebut: "2026-05-01",
    dateFin: "2026-08-01",
    createdAt: "2026-04-28T11:00:00Z",
  },
  {
    id: "diet-005",
    patientId: "pat-005",
    titre: "Régime hypoprotidique — Glomérulonéphrite",
    description: "Plan à teneur contrôlée en protéines pour réduire la charge glomérulaire.",
    category: "Régime hypoprotidique",
    content: "<h2>Objectifs du régime</h2><p>Réduire l'apport protidique à 0.8g/kg/jour pour diminuer l'hyperfiltration glomérulaire et ralentir la progression de la maladie.</p><h3>Répartition conseillée</h3><p>Matin : 15% des protéines — Midi : 45% — Soir : 40%</p><h3>Substituts protéiques</h3><p>Utiliser des préparations hypoprotidiques spéciales (pain, pâtes, riz) pour maintenir l'apport calorique sans augmenter les protéines.</p>",
    dateDebut: "2026-07-01",
    dateFin: "2026-10-01",
    createdAt: "2026-06-28T08:30:00Z",
  },
  {
    id: "diet-006",
    patientId: "pat-001",
    titre: "Régime pour dialyse — Hémodialyse",
    description: "Plan nutritionnel adapté aux séances d'hémodialyse pour compenser les pertes.",
    category: "Régime pour dialyse",
    content: "<h2>Objectifs du régime</h2><p>Assurer un apport protéique suffisant (1.2g/kg/jour) pour compenser les pertes pendant la dialyse, tout en contrôlant les électrolytes.</p><h3>Jour de dialyse</h3><p>Repas léger avant la séance. Collation protéinée pendant la séance. Repas normal après.</p><h3>Surveillance</h3><p>Poids entre les séances : prise de poids < 2.5% du poids sec. Apport hydrique limité selon la diurèse résiduelle.</p>",
    dateDebut: "2026-06-01",
    dateFin: "2026-12-31",
    createdAt: "2026-05-25T14:00:00Z",
  },
]

export const mockDocuments: Document[] = [
  {
    id: "doc-001",
    patientId: "pat-001",
    type: "Compte-rendu de consultation",
    titre: "CR Consultation — 10 Juin 2026",
    description: "Compte-rendu de la consultation de suivi MRC stade 3 avec bilan sanguin.",
    fileUrl: "/documents/cr-consultation-20260610.pdf",
    uploadedAt: "2026-06-10T10:30:00Z",
  },
  {
    id: "doc-002",
    patientId: "pat-001",
    type: "Bilan biologique",
    titre: "Bilan sanguin — Juin 2026",
    description: "Bilan complet : créatinine, urée, ionogramme, NFS, HbA1c.",
    fileUrl: "/documents/bilan-sanguin-20260610.pdf",
    uploadedAt: "2026-06-10T10:30:00Z",
  },
  {
    id: "doc-003",
    patientId: "pat-002",
    type: "Ordonnance",
    titre: "Ordonnance — Juin 2026",
    description: "Prescription : inhibiteur SGLT2, IEC, statine.",
    fileUrl: "/documents/ordonnance-20260615.pdf",
    uploadedAt: "2026-06-15T11:30:00Z",
  },
  {
    id: "doc-004",
    patientId: "pat-003",
    type: "Compte-rendu d'échographie",
    titre: "Échographie rénale — Avril 2026",
    description: "Échographie de contrôle post-greffe : bon aspect du greffon.",
    fileUrl: "/documents/echographie-20260422.pdf",
    uploadedAt: "2026-04-22T15:30:00Z",
  },
  {
    id: "doc-005",
    patientId: "pat-004",
    type: "Compte-rendu d'hospitalisation",
    titre: "CR Hospitalisation — Janvier 2026",
    description: "Hospitalisation pour colique néphrétique compliquée.",
    fileUrl: "/documents/cr-hospitalisation-20260115.pdf",
    uploadedAt: "2026-01-20T10:00:00Z",
  },
  {
    id: "doc-006",
    patientId: "pat-002",
    type: "Certificat médical",
    titre: "Certificat — Arrêt de travail",
    description: "Certificat d'arrêt de travail pour soins médicaux, 7 jours.",
    fileUrl: "/documents/certificat-20260620.pdf",
    uploadedAt: "2026-06-20T09:00:00Z",
  },
  {
    id: "doc-007",
    patientId: "pat-005",
    type: "Bilan biologique",
    titre: "Bilan annuel — Juillet 2026",
    description: "Bilan complet annuel incluant créatinine, protéinurie, DFG.",
    fileUrl: "/documents/bilan-annuel-20260702.pdf",
    uploadedAt: "2026-07-02T09:00:00Z",
  },
]

export const mockTestimonials: Testimonial[] = [
  {
    id: "test-001",
    patientId: "pat-001",
    patientNom: "Fatima Z.",
    note: 5,
    commentaire:
      "Le Dr Mezhoud m'a prise en charge avec beaucoup d'attention et de professionnalisme. Grâce à lui, ma maladie rénale est bien contrôlée. Je le recommande vivement.",
    date: "2026-05-20",
    visible: true,
  },
  {
    id: "test-002",
    patientId: "pat-002",
    patientNom: "Mohamed K.",
    note: 5,
    commentaire:
      "Un médecin à l'écoute, pédagogue et disponible. Il prend le temps d'expliquer chaque étape. Un grand professionnel.",
    date: "2026-04-15",
    visible: true,
  },
  {
    id: "test-003",
    patientId: "pat-003",
    patientNom: "Sarah B.",
    note: 5,
    commentaire:
      "Suivi impeccable pour ma greffe rénale. Le Dr Mezhoud est un expert dans son domaine et d'une grande humanité.",
    date: "2026-03-10",
    visible: true,
  },
  {
    id: "test-004",
    patientId: "pat-004",
    patientNom: "Karim D.",
    note: 4,
    commentaire:
      "Très bon néphrologue, à l'écoute et compétent. Le cabinet est bien situé et l'accueil est chaleureux.",
    date: "2026-02-28",
    visible: true,
  },
  {
    id: "test-005",
    patientId: "pat-005",
    patientNom: "Nadia A.",
    note: 5,
    commentaire:
      "Très satisfaite de ma consultation. Le docteur explique clairement et met en confiance. Je suis entre de bonnes mains.",
    date: "2026-06-25",
    visible: true,
  },
  {
    id: "test-006",
    patientId: "pat-002",
    patientNom: "Mohamed K.",
    note: 4,
    commentaire:
      "Consultation rapide mais complète. Le planning des rendez-vous est bien organisé. Je recommande.",
    date: "2025-11-10",
    visible: false,
  },
]

export const mockFAQs: FAQ[] = [
  {
    id: "faq-001",
    question: "Comment prendre rendez-vous ?",
    reponse:
      "Vous pouvez prendre rendez-vous en ligne via notre formulaire de rendez-vous, par téléphone au +213 21 63 12 45, ou en vous présentant directement au cabinet. Les rendez-vous sont confirmés sous 24h.",
    category: "Rendez-vous",
    ordre: 1,
  },
  {
    id: "faq-002",
    question: "Quels documents dois-je apporter à ma première consultation ?",
    reponse:
      "Pour une première consultation, apportez votre pièce d'identité, les ordonnances et bilans récents, la liste de vos médicaments actuels, les comptes-rendus hospitaliers si vous en avez, et votre carnet de santé.",
    category: "Consultation",
    ordre: 2,
  },
  {
    id: "faq-003",
    question: "Faut-il être à jeun pour une consultation ?",
    reponse:
      "Un jeûne n'est généralement pas nécessaire sauf si des analyses sanguines spécifiques sont prévues. Votre médecin vous informera au moment de la prise de rendez-vous si un jeûne est requis.",
    category: "Consultation",
    ordre: 3,
  },
  {
    id: "faq-004",
    question: "Quels sont les horaires d'ouverture du cabinet ?",
    reponse:
      "Le cabinet est ouvert du dimanche au jeudi de 08h30 à 16h30, et le vendredi de 08h30 à 12h00. Nous sommes fermés le samedi. En cas d'urgence, veuillez appeler notre numéro d'urgence au +213 770 12 34 56.",
    category: "Cabinet",
    ordre: 4,
  },
  {
    id: "faq-005",
    question: "Qu'est-ce que la créatinine et pourquoi la mesurer ?",
    reponse:
      "La créatinine est un déchet produit par les muscles et éliminé par les reins. Son taux dans le sang permet d'évaluer la fonction rénale. Un taux élevé peut indiquer une baisse du fonctionnement rénal. Le suivi régulier de la créatinine est essentiel dans les maladies rénales chroniques.",
    category: "Néphrologie",
    ordre: 5,
  },
  {
    id: "faq-006",
    question: "Qu'est-ce que le DFG (débit de filtration glomérulaire) ?",
    reponse:
      "Le DFG est le meilleur indicateur de la fonction rénale. Il calcule le volume de sang filtré par les reins par minute. Un DFG normal est supérieur à 90 mL/min/1.73m². En dessous de 60 pendant plus de 3 mois, on parle d'insuffisance rénale chronique.",
    category: "Néphrologie",
    ordre: 6,
  },
  {
    id: "faq-007",
    question: "Puis-je consulter pour un problème d'hypertension ?",
    reponse:
      "Oui, le Dr Mezhoud prend en charge l'hypertension artérielle, en particulier lorsqu'elle est liée à une maladie rénale. L'hypertension est à la fois une cause et une conséquence des maladies rénales. Une consultation spécialisée permet d'adapter le traitement à votre situation.",
    category: "Néphrologie",
    ordre: 7,
  },
  {
    id: "faq-008",
    question: "Comment puis-je obtenir mes résultats d'analyses ?",
    reponse:
      "Vos résultats d'analyses vous sont remis lors de votre consultation de suivi. Vous pouvez également les recevoir par email ou les télécharger depuis votre espace patient (prochainement disponible).",
    category: "Cabinet",
    ordre: 8,
  },
]

export const mockStats: DashboardStats = {
  totalPatients: 1247,
  consultationsJour: 12,
  consultationsMois: 89,
  nouveauxPatientsMois: 18,
  tauxOccupation: 78,
  rdvConfirmes: 42,
  rdvEnAttente: 8,
}

export const medecin: Medecin = {
  id: "dr-mezhoud-hadj",
  nom: "Mezhoud",
  prenom: "Hadj",
  specialite: "Néphrologie",
  titre: "Dr",
  bio: "Le Dr Mezhoud Hadj est néphrologue consultant avec plus de 15 ans d'expérience dans la prise en charge des maladies rénales. Formé à l'Université d'Alger et spécialisé en France, il exerce à Alger où il combine pratique clinique et engagement académique. Sa pratique est guidée par une approche centrée sur le patient, alliant rigueur scientifique et écoute active.",
  photo: "/images/doctor.jpg",
  email: "dr.mezhoud@cabinet.dz",
  telephone: "+213 21 63 12 45",
  diplomes: [
    "Doctorat en Médecine — Université d'Alger (2008)",
    "DES en Néphrologie — CHU Mustapha Pacha (2012)",
    "Diplôme Universitaire d'Hypertension Artérielle — Paris Descartes (2014)",
    "Master en Épidémiologie Clinique — Université d'Alger (2016)",
  ],
  experiences: [
    {
      annee: "2018 – Présent",
      titre: "Néphrologue Consultant",
      lieu: "Cabinet Privé, Alger",
      description: "Consultations spécialisées en néphrologie, suivi des maladies rénales chroniques, dialyse et transplantation.",
    },
    {
      annee: "2013 – 2018",
      titre: "Assistant Hospitalo-Universitaire",
      lieu: "CHU Mustapha Pacha, Alger",
      description: "Prise en charge des patients hospitalisés en néphrologie, enseignement universitaire et participation à des projets de recherche.",
    },
    {
      annee: "2012 – 2013",
      titre: "Fellowship en Néphrologie",
      lieu: "Hôpital Necker, Paris",
      description: "Spécialisation en transplantation rénale et maladies glomérulaires.",
    },
  ],
  horaires: [
    { jour: "Dimanche – Jeudi", matin: "08h30 – 12h00", apresMidi: "13h00 – 16h30" },
    { jour: "Vendredi", matin: "08h30 – 12h00", apresMidi: "Fermé" },
    { jour: "Samedi", matin: "Fermé", apresMidi: "Fermé" },
  ],
}

export const cabinet: Cabinet = {
  nom: "Cabinet de Néphrologie — Dr Mezhoud Hadj",
  adresse: "42 Rue Didouche Mourad",
  ville: "Alger Centre",
  codePostal: "16000",
  telephone: "+213 21 63 12 45",
  email: "contact@drmezhoud.dz",
  urgence: "+213 770 12 34 56",
  description: "Notre cabinet est un espace moderne et chaleureux dédié à la santé rénale. Situé en plein cœur d'Alger, il est facilement accessible et conçu pour offrir à nos patients un environnement serein et professionnel.",
  services: [
    "Consultations de néphrologie générale",
    "Suivi des maladies rénales chroniques (MRC)",
    "Prise en charge de l'hypertension artérielle",
    "Dépistage et suivi du diabète",
    "Échographie rénale et Doppler",
    "Bilans pré et post-transplantation",
    "Coordination dialyse",
    "Conseil génétique en néphrologie",
  ],
  equipements: [
    "Salle de consultation avec échographe",
    "Appareil de mesure de la pression artérielle MAPA",
    "Analyseur de bandelette urinaire",
    "ECG numérique",
    "Salle d'attente climatisée",
    "Espace dédié aux soins infirmiers",
  ],
  photos: [],
}

export const pathologies: Pathologie[] = [
  {
    id: "insuffisance-renale-chronique",
    nom: "Insuffisance Rénale Chronique",
    description: "Perte progressive et irréversible de la fonction rénale sur plusieurs mois ou années. C'est une affection silencieuse qui peut évoluer vers le stade terminal nécessitant dialyse ou transplantation.",
    symptomes: [
      "Fatigue et faiblesse générale",
      "Œdèmes (chevilles, jambes, paupières)",
      "Essoufflement",
      "Nausées et perte d'appétit",
      "Démangeaisons cutanées",
      "Crampes musculaires nocturnes",
    ],
    causes: [
      "Diabète de type 1 et 2",
      "Hypertension artérielle",
      "Glomérulonéphrites",
      "Maladies héréditaires (polykystose rénale)",
      "Infections rénales chroniques",
      "Obstruction des voies urinaires",
    ],
    traitements: [
      "Régime alimentaire adapté (pauvre en sel, potassium, phosphore)",
      "Médicaments antihypertenseurs",
      "Traitement de l'anémie",
      "Dialyse (hémodialyse ou dialyse péritonéale)",
      "Transplantation rénale",
    ],
    icone: "Shield",
  },
  {
    id: "hypertension-arterielle",
    nom: "Hypertension Artérielle",
    description: "Élévation chronique de la pression artérielle, facteur de risque majeur pour les maladies rénales et cardiovasculaires. Le rein joue un rôle central dans la régulation de la pression artérielle.",
    symptomes: [
      "Souvent asymptomatique (tueur silencieux)",
      "Céphalées matinales",
      "Vertiges",
      "Bourdonnements d'oreille",
      "Palpitations",
      "Troubles visuels",
    ],
    causes: [
      "Facteurs génétiques",
      "Alimentation riche en sel",
      "Sédentarité et obésité",
      "Stress chronique",
      "Tabagisme et alcool",
      "Maladies rénales sous-jacentes",
    ],
    traitements: [
      "Régime hyposodé (réduction du sel)",
      "Activité physique régulière",
      "Médicaments antihypertenseurs",
      "Arrêt du tabac et modération de l'alcool",
      "Gestion du stress",
    ],
    icone: "HeartPulse",
  },
  {
    id: "glomerulonephrite",
    nom: "Glomérulonéphrite",
    description: "Inflammation des glomérules, les unités filtrantes du rein. Peut être aiguë ou chronique, primitive ou secondaire à d'autres maladies.",
    symptomes: [
      "Urines foncées (couleur cola ou thé)",
      "Présence de sang ou de protéines dans les urines",
      "Œdèmes du visage et des membres",
      "Hypertension artérielle",
      "Diminution du volume urinaire",
    ],
    causes: [
      "Infections (streptocoques, hépatites, VIH)",
      "Maladies auto-immunes (lupus)",
      "Vascularites",
      "Médicaments",
      "Causes génétiques rares",
    ],
    traitements: [
      "Corticothérapie et immunosuppresseurs",
      "Traitement antihypertenseur",
      "Régime pauvre en sel et protéines",
      "Diurétiques",
      "Dialyse dans les formes sévères",
    ],
    icone: "Droplets",
  },
  {
    id: "lithiase-urinaire",
    nom: "Lithiase Urinaire",
    description: "Formation de calculs dans les reins ou les voies urinaires. La prévalence est en augmentation, touchant environ 10% de la population.",
    symptomes: [
      "Douleur lombaire intense et brutale (colique néphrétique)",
      "Sang dans les urines",
      "Brûlures urinaires",
      "Nausées et vomissements",
      "Fièvre en cas d'infection associée",
    ],
    causes: [
      "Déshydratation chronique",
      "Alimentation riche en sel, oxalates, purines",
      "Hyperparathyroïdie",
      "Infections urinaires",
      "Anomalies métaboliques",
    ],
    traitements: [
      "Hydratation abondante (2-3L/jour)",
      "Traitement médicamenteux de la douleur",
      "Médicaments dissolvants (certains types de calculs)",
      "Lithotritie extracorporelle",
      "Urétéroscopie ou chirurgie",
    ],
    icone: "Scan",
  },
  {
    id: "insuffisance-renale-aigue",
    nom: "Insuffisance Rénale Aiguë",
    description: "Détérioration rapide de la fonction rénale (heures à jours). Potentiellement réversible si prise en charge rapide et adaptée.",
    symptomes: [
      "Diminution brutale du volume urinaire",
      "Fatigue extrême",
      "Confusion mentale",
      "Nausées et vomissements",
      "Œdèmes généralisés",
      "Essoufflement",
    ],
    causes: [
      "Déshydratation sévère (diarrhées, vomissements)",
      "Médicaments néphrotoxiques",
      "Infections graves (sepsis)",
      "Obstruction urinaire aiguë",
      "Choc cardiogénique",
    ],
    traitements: [
      "Hydratation intraveineuse",
      "Arrêt des médicaments néphrotoxiques",
      "Traitement de la cause sous-jacente",
      "Dialyse temporaire si nécessaire",
      "Surveillance rapprochée de la fonction rénale",
    ],
    icone: "Activity",
  },
  {
    id: "polykystose-renale",
    nom: "Polykystose Rénale",
    description: "Maladie génétique caractérisée par le développement de multiples kystes dans les reins, entraînant une augmentation de leur volume et une perte progressive de leur fonction.",
    symptomes: [
      "Hypertension artérielle",
      "Douleurs lombaires chroniques",
      "Sang dans les urines",
      "Infections urinaires fréquentes",
      "Lithiases rénales",
      "Augmentation du volume abdominal",
    ],
    causes: [
      "Mutation génétique héréditaire (autosomique dominante)",
      "Antécédents familiaux de polykystose",
      "Forme récessive rare (diagnostic précoce)",
    ],
    traitements: [
      "Suivi néphrologique régulier",
      "Contrôle strict de la tension artérielle",
      "Hydratation abondante",
      "Traitement des complications (infections, douleur)",
      "Dialyse et transplantation au stade terminal",
    ],
    icone: "Shield",
  },
]

export const articles: Article[] = [
  {
    id: "1",
    slug: "comprendre-sa-prise-de-sang-creatinine",
    titre: "Comprendre sa prise de sang : la créatinine",
    resume: "La créatinine est un marqueur essentiel de la fonction rénale. Découvrez comment interpréter vos résultats et quand s'inquiéter.",
    contenu: "La créatinine est un déchet produit par les muscles et éliminé par les reins. Son taux dans le sang est un indicateur clé de la fonction rénale...",
    auteur: "Dr Mezhoud Hadj",
    date: "2026-06-15",
    image: "/images/blog/creatinine.jpg",
    tags: ["Néphrologie", "Bilan", "Prévention"],
    lectureMin: 5,
  },
  {
    id: "2",
    slug: "alimentation-et-maladie-renale",
    titre: "Alimentation et maladie rénale : les bases à connaître",
    resume: "Une alimentation adaptée est cruciale pour ralentir la progression des maladies rénales. Voici les principes fondamentaux.",
    contenu: "L'alimentation joue un rôle central dans la prise en charge des maladies rénales. Un régime adapté permet de ralentir la progression de l'insuffisance rénale...",
    auteur: "Dr Mezhoud Hadj",
    date: "2026-05-28",
    image: "/images/blog/alimentation.jpg",
    tags: ["Nutrition", "MRC", "Prévention"],
    lectureMin: 7,
  },
  {
    id: "3",
    slug: "hypertension-et-reins-lien-invisible",
    titre: "Hypertension et reins : le lien invisible",
    resume: "L'hypertension est à la fois une cause et une conséquence des maladies rénales. Comprendre ce cercle vicieux pour mieux le briser.",
    contenu: "Les reins et la pression artérielle entretiennent une relation complexe. Les reins régulent la pression artérielle, mais sont aussi ses premières victimes...",
    auteur: "Dr Mezhoud Hadj",
    date: "2026-04-10",
    image: "/images/blog/hypertension.jpg",
    tags: ["Hypertension", "Cardio-rénal", "Prévention"],
    lectureMin: 6,
  },
  {
    id: "4",
    slug: "depistage-precoce-maladie-renale",
    titre: "L'importance du dépistage précoce des maladies rénales",
    resume: "Les maladies rénales sont souvent silencieuses. Un dépistage simple peut faire la différence. Qui doit se faire dépister et comment ?",
    contenu: "On estime qu'une personne sur dix souffre d'une maladie rénale chronique, mais la plupart l'ignorent. Le dépistage précoce est essentiel...",
    auteur: "Dr Mezhoud Hadj",
    date: "2026-03-22",
    image: "/images/blog/depistage.jpg",
    tags: ["Prévention", "Dépistage", "Sensibilisation"],
    lectureMin: 4,
  },
  {
    id: "5",
    slug: "hydratation-et-sante-renale",
    titre: "Hydratation et santé rénale : mythes et réalités",
    resume: "Boire beaucoup d'eau est-il toujours bon pour les reins ? Démêlons le vrai du faux sur l'hydratation.",
    contenu: "L'hydratation est essentielle au bon fonctionnement des reins, mais ses besoins varient selon les situations...",
    auteur: "Dr Mezhoud Hadj",
    date: "2026-02-14",
    image: "/images/blog/hydratation.jpg",
    tags: ["Hydratation", "Prévention", "Nutrition"],
    lectureMin: 5,
  },
  {
    id: "6",
    slug: "medicaments-et-reins-precautions",
    titre: "Médicaments et reins : les précautions à prendre",
    resume: "Certains médicaments courants peuvent être toxiques pour les reins. Apprenez à les reconnaître et à les utiliser en toute sécurité.",
    contenu: "De nombreux médicaments, y compris certains en vente libre, peuvent affecter la fonction rénale...",
    auteur: "Dr Mezhoud Hadj",
    date: "2026-01-08",
    image: "/images/blog/medicaments.jpg",
    tags: ["Médicaments", "Sécurité", "Prévention"],
    lectureMin: 6,
  },
  {
    id: "7",
    slug: "diabete-et-reins-prevenir-neuropathie",
    titre: "Diabète et reins : comment prévenir la néphropathie diabétique ?",
    resume: "Le diabète est la première cause d'insuffisance rénale terminale. Des mesures préventives existent pour protéger vos reins.",
    contenu: "La néphropathie diabétique touche environ 30% des patients diabétiques. Un bon contrôle glycémique et une surveillance régulière permettent de ralentir son évolution...",
    auteur: "Dr Mezhoud Hadj",
    date: "2025-12-01",
    image: "/images/blog/diabete.jpg",
    tags: ["Diabète", "Néphropathie", "Prévention"],
    lectureMin: 7,
  },
  {
    id: "8",
    slug: "activite-physique-maladie-renale",
    titre: "Activité physique et maladie rénale : ce qu'il faut savoir",
    resume: "Pratiquer une activité physique régulière est bénéfique même en cas d'insuffisance rénale. Quels sports pratiquer et à quelle intensité ?",
    contenu: "L'activité physique adaptée améliore la qualité de vie des patients rénaux chroniques...",
    auteur: "Dr Mezhoud Hadj",
    date: "2025-11-10",
    image: "/images/blog/sport.jpg",
    tags: ["Activité physique", "MRC", "Bien-être"],
    lectureMin: 5,
  },
]

export const temoignages: Temoignage[] = [
  {
    id: "1",
    patient: "Fatima Z.",
    note: 5,
    commentaire: "Le Dr Mezhoud m'a prise en charge avec beaucoup d'attention et de professionnalisme. Grâce à lui, ma maladie rénale est bien contrôlée. Je le recommande vivement.",
    date: "2026-05-20",
    initiales: "FZ",
  },
  {
    id: "2",
    patient: "Mohamed K.",
    note: 5,
    commentaire: "Un médecin à l'écoute, pédagogue et disponible. Il prend le temps d'expliquer chaque étape. Un grand professionnel.",
    date: "2026-04-15",
    initiales: "MK",
  },
  {
    id: "3",
    patient: "Sarah B.",
    note: 5,
    commentaire: "Suivi impeccable pour ma greffe rénale. Le Dr Mezhoud est un expert dans son domaine et d'une grande humanité.",
    date: "2026-03-10",
    initiales: "SB",
  },
  {
    id: "4",
    patient: "Karim D.",
    note: 4,
    commentaire: "Très bon néphrologue, à l'écoute et compétent. Le cabinet est bien situé et l'accueil est chaleureux.",
    date: "2026-02-28",
    initiales: "KD",
  },
]

export const parcoursEtapes: EtapeParcours[] = [
  {
    id: "accueil",
    titre: "Accueil & Prise de contact",
    description: "Premier contact par téléphone ou via le formulaire en ligne. Notre secrétariat vous oriente et planifie votre rendez-vous.",
    duree: "Quelques minutes",
    icone: "Phone",
  },
  {
    id: "consultation",
    titre: "Consultation initiale",
    description: "Entretien détaillé avec le Dr Mezhoud : historique médical, antécédents, symptômes actuels. Examen clinique complet.",
    duree: "45 – 60 min",
    icone: "Stethoscope",
  },
  {
    id: "bilan",
    titre: "Bilan complémentaire",
    description: "Prescription d'examens biologiques (sang, urine) et d'imagerie si nécessaire pour établir un diagnostic précis.",
    duree: "1 – 7 jours",
    icone: "FileText",
  },
  {
    id: "diagnostic",
    titre: "Diagnostic & Traitement",
    description: "Analyse des résultats, annonce du diagnostic, proposition du plan thérapeutique personnalisé et réponses à vos questions.",
    duree: "Consultation dédiée",
    icone: "ClipboardList",
  },
  {
    id: "suivi",
    titre: "Suivi personnalisé",
    description: "Consultations de suivi régulières pour ajuster le traitement, surveiller l'évolution et maintenir un dialogue ouvert.",
    duree: "Selon le protocole",
    icone: "Calendar",
  },
]

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug)
}

export function getPathologieById(id: string): Pathologie | undefined {
  return pathologies.find((p) => p.id === id)
}

// ── Backward-compat aliases (remove when pages migrate to new types) ──
export const services: Array<{
  id: string
  titre: string
  description: string
  icone: string
}> = mockServices.map((s) => ({
  id: s.id,
  titre: s.nom,
  description: s.description,
  icone: s.icone,
}))
